name: LevelUpBio
favicon: null
layout_spectrum: 0.3323126300238073
typography_spectrum: 0.48567272489890456
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7575322249904275
  lightness: 0.26578714116476476
  saturation: 0.17831470794044435
  rhythmicContrast: 0.07831152551807463
purpose: []
